# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         pmv
version:      0.03
version_from: script/pmv
installdirs:  site
requires:
    File::Basename:                0
    File::Path:                    0
    Getopt::Long:                  2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
